# This is base config

[base]
    debug_mode="debug"
    time_location="Asia/Chongqing"

[http]
    addr =":8880"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 10                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    allow_ip = [                        # 白名单ip列表
        "127.0.0.1",
        "192.168.1.1"
    ]

[log]
    log_level = "trace"         #日志打印最低级别
    [log.file_writer]           #文件写入配置
        on = true
        log_path = "./gininit.inf.log"
        rotate_log_path = "./gin_init.inf.log"
        wf_log_path = "./gininit.wf.log"
        rotate_wf_log_path = "./gin_scaffold.wf.log"
    [log.console_writer]        #工作台输出
        on = false
        color = false


[gormTools]
    out_dir = "."  # 输出目录
    singular_table = false  # 表名复数,是否大驼峰构建 参考:gorm.SingularTable
    simple = false #简单输出
    is_out_sql = false # 是否输出 sql 原信息
    is_json_tag = false #是否打json标记
    is_foreign_key = true #是否导出外键关联
    [mysql_info]
        host = "127.0.0.1"
        port = 3306
        username = "root"
        password = ""
        database = "gin"